package UIFrame.DialogTasks;

import controller.CustomerController;
import java.util.List;
import javax.swing.JOptionPane;
import model.CustomerModel;
import model.LoanModel;
import model.SavingAccountModel;

/**
 *
 * @author ACER
 */
public class PaymentForLoan extends javax.swing.JDialog {

    private CustomerModel customerModel;
    private CustomerController customerController;

    public PaymentForLoan(java.awt.Frame parent, boolean modal, CustomerModel customerModel, CustomerController customerController) {
        super(parent, modal);
        this.customerModel = customerModel;
        this.customerController = customerController;
        initComponents();
        onLoadCMBX();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbxSaving = new javax.swing.JComboBox<>();
        cmbxLoan = new javax.swing.JComboBox<>();
        txtAmount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtError = new javax.swing.JLabel();
        btndirectly = new javax.swing.JButton();
        btnsaving = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbxSaving.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbxSaving.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxSaving.setBorder(null);

        cmbxLoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbxLoan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("PAYMENT");

        a.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        a.setText("Saving Account");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Loan Number");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Amount");

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("$");

        txtError.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 0, 0));

        btndirectly.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndirectly.setText("Directly");
        btndirectly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndirectlyActionPerformed(evt);
            }
        });

        btnsaving.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsaving.setText("Pay with saving account");
        btnsaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(a)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbxSaving, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbxLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btndirectly)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnsaving)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(cmbxSaving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbxLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btndirectly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsaving)
                .addGap(43, 43, 43)
                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onLoadCMBX() {
        String a = customerModel.getCustomer_id();
        this.cmbxLoan.removeAllItems();
        this.cmbxSaving.removeAllItems();

        List<SavingAccountModel> savingAccountList = customerController.findAllSavingAccount(a);
        List<LoanModel> loanModelList = customerController.findAllLoan(a);
        for (int i = 0; i < savingAccountList.size(); i++) {
            this.cmbxSaving.addItem(savingAccountList.get(i).getAccountNumber());
        }
        for (int i = 0; i < loanModelList.size(); i++) {
            this.cmbxLoan.addItem("" + loanModelList.get(i).getLoanNumber());
        }
    }

    private void doSubmit() {
        String savingsAccount = this.cmbxSaving.getSelectedItem().toString();
        int loanNumber = Integer.parseInt(this.cmbxLoan.getSelectedItem().toString());
        if (this.txtAmount.getText().isBlank()) {
            this.txtError.setText("Please fill data first!");
        } else {
            Double amount = Double.valueOf(this.txtAmount.getText());
            String result = null;

            if (cmbxSaving.isShowing()) {
                result = customerController.paymenWithSavingAccount(savingsAccount, loanNumber, amount);
            } else {
                result = customerController.paymenWithoutSavingAccount(loanNumber, amount);
            }

            if (result != null) {
                if ("oke".equals(result)) {
                    JOptionPane.showMessageDialog(rootPane, "Payment successfull for " + loanNumber);
                } else if (result.equals("justneedtopayenough")) {
                    JOptionPane.showMessageDialog(rootPane, "You payment is over your loan");
                } else if (result.equals("lessthan50")) {
                    JOptionPane.showMessageDialog(rootPane, "Your savings account can not less than 50$");
                } else if (result.equals("lessthan50")) {
                    JOptionPane.showMessageDialog(rootPane, "Your savings account can not less than 50$");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Transfer Error!");
            }
        }

    }


    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        doSubmit();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btndirectlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndirectlyActionPerformed
        // TODO add your handling code here:
        this.a.setVisible(false);
        this.cmbxSaving.setVisible(false);

    }//GEN-LAST:event_btndirectlyActionPerformed

    private void btnsavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavingActionPerformed
        // TODO add your handling code here:
        this.a.setVisible(true);
        this.cmbxSaving.setVisible(true);
    }//GEN-LAST:event_btnsavingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btndirectly;
    private javax.swing.JButton btnsaving;
    private javax.swing.JComboBox<String> cmbxLoan;
    private javax.swing.JComboBox<String> cmbxSaving;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JLabel txtError;
    // End of variables declaration//GEN-END:variables
}
